repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.2  # Use the latest stable version
    hooks:
      - id: ruff
        args: [--fix]  # Automatically fix issues when possible