name: Build and publish Docker images

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.3.0
        with:
          cosign-release: 'v2.2.2'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build, tag, and push the training image
      - name: Build and push training image
        id: build-train
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: dockerfiles/train.dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-train:latest
          push: ${{ github.event_name != 'pull_request' }}

      # Build, tag, and push the API image
      - name: Build and push API image
        id: build-api
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: dockerfiles/api.dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:latest
          push: ${{ github.event_name != 'pull_request' }}

      # Build, tag, and push the evaluation image
      - name: Build and push evaluation image
        id: build-evaluate
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: dockerfiles/evaluate.dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-evaluate:latest
          push: ${{ github.event_name != 'pull_request' }}

      - name: Sign the published Docker images
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TRAIN_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-train:latest
          API_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api:latest
          EVALUATE_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-evaluate:latest
        run: |
          cosign sign --yes ${TRAIN_TAG}
          cosign sign --yes ${API_TAG}
          cosign sign --yes ${EVALUATE_TAG}
